spring:
  application:
    name: VacationPayCalculator
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: ${PG_DATABASE_URL}
    username: ${PG_DATABASE_USERNAME}
    password: ${PG_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    current_session_context_class: thread